CREATE DATABASE IF NOT EXISTS enchainte_db;

USE enchainte_db;

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id CHAR(36) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_on VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS products;

CREATE TABLE IF NOT EXISTS products (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(13,2) NOT NULL,
    seller_id CHAR(36) NOT NULL,
    created_on VARCHAR(255) NOT NULL,
    updated_on VARCHAR(255) NOT NULL DEFAULT "",
    FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE
);